package GUI;

import java.awt.Image;
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vans
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setTitle("EasyBros");
        this.setResizable(false);
        this.setSize(500, 280);
        this.setLocationRelativeTo(null);
        //this.setVisible(true);
        this.setDefaultCloseOperation(GUI.EXIT_ON_CLOSE);
    }

    // Agregamos un icono SobreEscribimos el Metodo
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Recursos/mario_icon.png"));
        return retValue;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Mario = new javax.swing.JLabel();
        Moneda_1 = new javax.swing.JLabel();
        Moneda_2 = new javax.swing.JLabel();
        Moneda_3 = new javax.swing.JLabel();
        Moneda_5 = new javax.swing.JLabel();
        Moneda_6 = new javax.swing.JLabel();
        Moneda_4 = new javax.swing.JLabel();
        Moneda_7 = new javax.swing.JLabel();
        Moneda_8 = new javax.swing.JLabel();
        JL_Puff = new javax.swing.JLabel();
        JL_Marcador = new javax.swing.JLabel();
        JL_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(null);

        JL_Mario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Static.png"))); // NOI18N
        getContentPane().add(JL_Mario);
        JL_Mario.setBounds(10, 170, 50, 50);

        Moneda_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        getContentPane().add(Moneda_1);
        Moneda_1.setBounds(50, 130, 31, 40);

        Moneda_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        getContentPane().add(Moneda_2);
        Moneda_2.setBounds(90, 130, 31, 40);

        Moneda_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        getContentPane().add(Moneda_3);
        Moneda_3.setBounds(190, 180, 31, 40);

        Moneda_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        getContentPane().add(Moneda_5);
        Moneda_5.setBounds(340, 180, 31, 40);

        Moneda_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        getContentPane().add(Moneda_6);
        Moneda_6.setBounds(380, 180, 31, 40);

        Moneda_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        getContentPane().add(Moneda_4);
        Moneda_4.setBounds(230, 180, 31, 40);

        Moneda_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        getContentPane().add(Moneda_7);
        Moneda_7.setBounds(440, 130, 31, 40);

        Moneda_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        getContentPane().add(Moneda_8);
        Moneda_8.setBounds(290, 130, 31, 40);

        JL_Puff.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JL_Puff.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JL_Puff);
        JL_Puff.setBounds(150, 70, 270, 40);

        JL_Marcador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_Marcador.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JL_Marcador);
        JL_Marcador.setBounds(140, 20, 30, 20);

        JL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BackGround.png"))); // NOI18N
        getContentPane().add(JL_Fondo);
        JL_Fondo.setBounds(0, 0, 499, 247);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //if ("Nimbus".equals(info.getName())) {
                   // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   // break;
                //}
           // }
        //} catch (ClassNotFoundException ex) {
        //    java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
        //    java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
        //    java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //    java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JL_Fondo;
    public javax.swing.JLabel JL_Marcador;
    public javax.swing.JLabel JL_Mario;
    public javax.swing.JLabel JL_Puff;
    public javax.swing.JLabel Moneda_1;
    public javax.swing.JLabel Moneda_2;
    public javax.swing.JLabel Moneda_3;
    public javax.swing.JLabel Moneda_4;
    public javax.swing.JLabel Moneda_5;
    public javax.swing.JLabel Moneda_6;
    public javax.swing.JLabel Moneda_7;
    public javax.swing.JLabel Moneda_8;
    // End of variables declaration//GEN-END:variables
}
